"""refactor_sensor_tables_v2

Revision ID: 694a97213b94
Revises: 
Create Date: 2026-02-17 11:20:55.374170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '694a97213b94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('tilt_x', sa.Float(), nullable=False),
    sa.Column('tilt_y', sa.Float(), nullable=False),
    sa.Column('tilt_z', sa.Float(), nullable=False),
    sa.Column('distance_cm', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_sensor_data_created_at'), 'raw_sensor_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_raw_sensor_data_device_id'), 'raw_sensor_data', ['device_id'], unique=False)
    op.create_index(op.f('ix_raw_sensor_data_id'), 'raw_sensor_data', ['id'], unique=False)
    op.create_table('processed_sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('raw_data_id', sa.Integer(), nullable=False),
    sa.Column('tilt_diff_x', sa.Float(), nullable=False),
    sa.Column('tilt_diff_y', sa.Float(), nullable=False),
    sa.Column('tilt_diff_z', sa.Float(), nullable=False),
    sa.Column('distance_diff_cm', sa.Float(), nullable=False),
    sa.Column('tilt_change_percent', sa.Float(), nullable=False),
    sa.Column('distance_change_percent', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['raw_data_id'], ['raw_sensor_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_data_id')
    )
    op.create_index(op.f('ix_processed_sensor_data_created_at'), 'processed_sensor_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_processed_sensor_data_device_id'), 'processed_sensor_data', ['device_id'], unique=False)
    op.create_index(op.f('ix_processed_sensor_data_id'), 'processed_sensor_data', ['id'], unique=False)
    op.drop_table('user_device_access')
    op.drop_index(op.f('ix_sensor_readings_created_at'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_device_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.add_column('devices', sa.Column('tilt_warning_threshold', sa.Float(), nullable=False, server_default='30.0'))
    op.add_column('devices', sa.Column('tilt_alert_threshold', sa.Float(), nullable=False, server_default='50.0'))
    op.add_column('devices', sa.Column('distance_warning_threshold', sa.Float(), nullable=False, server_default='30.0'))
    op.add_column('devices', sa.Column('distance_alert_threshold', sa.Float(), nullable=False, server_default='50.0'))
    op.drop_column('devices', 'distance_threshold_percent')
    op.drop_column('devices', 'tilt_threshold_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('tilt_threshold_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('distance_threshold_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('devices', 'distance_alert_threshold')
    op.drop_column('devices', 'distance_warning_threshold')
    op.drop_column('devices', 'tilt_alert_threshold')
    op.drop_column('devices', 'tilt_warning_threshold')
    op.create_table('sensor_readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tilt_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tilt_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tilt_z', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('distance_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tilt_change_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('distance_change_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tilt_threshold_breached', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('distance_threshold_breached', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_sent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('sensor_readings_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sensor_readings_pkey'))
    )
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_device_id'), 'sensor_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_created_at'), 'sensor_readings', ['created_at'], unique=False)
    op.create_table('user_device_access',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_level', postgresql.ENUM('ADMIN', 'VIEWER', name='userdeviceaccesslevel'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('user_device_access_device_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_device_access_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'device_id', name=op.f('user_device_access_pkey'))
    )
    op.drop_index(op.f('ix_processed_sensor_data_id'), table_name='processed_sensor_data')
    op.drop_index(op.f('ix_processed_sensor_data_device_id'), table_name='processed_sensor_data')
    op.drop_index(op.f('ix_processed_sensor_data_created_at'), table_name='processed_sensor_data')
    op.drop_table('processed_sensor_data')
    op.drop_index(op.f('ix_raw_sensor_data_id'), table_name='raw_sensor_data')
    op.drop_index(op.f('ix_raw_sensor_data_device_id'), table_name='raw_sensor_data')
    op.drop_index(op.f('ix_raw_sensor_data_created_at'), table_name='raw_sensor_data')
    op.drop_table('raw_sensor_data')
    # ### end Alembic commands ###
